// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY_vsY9PaDJmlf5yx1nS8pDu8Tkyq6Kso',
    appId: '1:260226399516:web:79eb5034309581c4858ed9',
    messagingSenderId: '260226399516',
    projectId: 'fcupay-454e8',
    authDomain: 'fcupay-454e8.firebaseapp.com',
    storageBucket: 'fcupay-454e8.appspot.com',
    measurementId: 'G-7TWZWY92H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8IMbyoyRWnJdGoRM_RBeAh4NCiPwDDsY',
    appId: '1:260226399516:android:6a5f3380053410ad858ed9',
    messagingSenderId: '260226399516',
    projectId: 'fcupay-454e8',
    storageBucket: 'fcupay-454e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1MJM5bWhkoEVAfZAQC_o-ccbKdJopfYc',
    appId: '1:260226399516:ios:3a648136c9ab0d0b858ed9',
    messagingSenderId: '260226399516',
    projectId: 'fcupay-454e8',
    storageBucket: 'fcupay-454e8.appspot.com',
    iosClientId:
        '260226399516-raocv3nt1v39cvnu0eqohqu01vk9set5.apps.googleusercontent.com',
    iosBundleId: 'com.tonypepe.fengchiabi',
  );
}
